
[[main]]
name = "CognWare"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "About"
weight = 2

[[main]]
name = "Scroll"
pageRef = "scroll"
weight = 2

[[main]]
name = "Posts"
pageRef = "posts"
weight = 3

[[main]]
name = "Invest"
PageRef = "invest"
weight = 4

[[main]]
name = "Offerings"
PageRef = "offerings"
weight = 4

[[footer]]
name = "Github"
pre = "github"
url = "https://github.com/CognWare-Industries"
weight = 1

[[footer]]
name = "Youtube"
pre = "youtube"
url = "https://www.youtube.com/@CognWare"
weight = 1
