# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "bitmage"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

replyByEmail = false

mainSections = ["posts",]
# robots = ""

disableImageOptimization = false
disableTextInHeader = true
backgroundImageWidth = 1200

#defaultBackgroundImage = "img/retrofractal_web_optimized.webp" # used as default for background images
#defaultFeaturedImage = "img/retrofractal_web_optimized.webp" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true
# smartTOCHideUnfocusedChildren = true

giteadefaultserver = "https://git.fsfe.org"
forgejodefaultserver = "https://v8.next.forgejo.org"

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/retrofractal_web_optimized.webp" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = true
  showAuthor = true
  showAuthorBottom = true
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
   showRelatedContent = false
  #Â relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  websiteid = "59b4351b-769b-4384-a8e5-031a30b901c7"
  domain = "cognware.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  # fediverse = ""

[rssnext]
  # feedId = ""
  # userId = ""
